set_property PACKAGE_PIN D17 [get_ports clk]

set_property PACKAGE_PIN Y2 [get_ports resetn]


set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS25 [get_ports resetn]

set_property IOSTANDARD LVCMOS33 [get_ports LED]

set_property PACKAGE_PIN F20 [get_ports LED]

set_property PACKAGE_PIN T5 [get_ports {LA_in_p[0]}]
set_property PACKAGE_PIN U5 [get_ports {LA_in_n[0]}]
set_property PACKAGE_PIN H4 [get_ports {LA_out_p[0]}]
set_property PACKAGE_PIN G4 [get_ports {LA_out_n[0]}]

set_property PACKAGE_PIN Y4 [get_ports {LA_in_p[1]}]
set_property PACKAGE_PIN AA4 [get_ports {LA_in_n[1]}]
set_property PACKAGE_PIN K4 [get_ports {LA_out_p[1]}]
set_property PACKAGE_PIN J4 [get_ports {LA_out_n[1]}]

set_property PACKAGE_PIN L3 [get_ports {LA_in_p[2]}]
set_property PACKAGE_PIN K3 [get_ports {LA_in_n[2]}]
set_property PACKAGE_PIN M1 [get_ports {LA_out_p[2]}]
set_property PACKAGE_PIN L1 [get_ports {LA_out_n[2]}]

set_property PACKAGE_PIN H2 [get_ports {LA_in_p[3]}]
set_property PACKAGE_PIN G2 [get_ports {LA_in_n[3]}]
set_property PACKAGE_PIN W6 [get_ports {LA_out_p[3]}]
set_property PACKAGE_PIN W5 [get_ports {LA_out_n[3]}]

set_property PACKAGE_PIN AA1 [get_ports {LA_in_p[4]}]
set_property PACKAGE_PIN AB1 [get_ports {LA_in_n[4]}]
set_property PACKAGE_PIN K1 [get_ports {LA_out_p[4]}]
set_property PACKAGE_PIN J1 [get_ports {LA_out_n[4]}]

set_property PACKAGE_PIN M3 [get_ports {LA_in_p[5]}]
set_property PACKAGE_PIN M2 [get_ports {LA_in_n[5]}]
set_property PACKAGE_PIN Y6 [get_ports {LA_out_p[5]}]
set_property PACKAGE_PIN AA6 [get_ports {LA_out_n[5]}]

set_property PACKAGE_PIN AB3 [get_ports {LA_in_p[6]}]
set_property PACKAGE_PIN AB2 [get_ports {LA_in_n[6]}]
set_property PACKAGE_PIN U6 [get_ports {LA_out_p[6]}]
set_property PACKAGE_PIN V5 [get_ports {LA_out_n[6]}]

set_property PACKAGE_PIN W1 [get_ports {LA_in_p[7]}]
set_property PACKAGE_PIN Y1 [get_ports {LA_in_n[7]}]
set_property PACKAGE_PIN G1 [get_ports {LA_out_p[7]}]
set_property PACKAGE_PIN F1 [get_ports {LA_out_n[7]}]

set_property PACKAGE_PIN K2 [get_ports {LA_in_p[8]}]
set_property PACKAGE_PIN J2 [get_ports {LA_in_n[8]}]
set_property PACKAGE_PIN W9 [get_ports {LA_out_p[8]}]
set_property PACKAGE_PIN Y9 [get_ports {LA_out_n[8]}]

set_property PACKAGE_PIN R3 [get_ports {LA_in_p[9]}]
set_property PACKAGE_PIN R2 [get_ports {LA_in_n[9]}]
set_property PACKAGE_PIN V7 [get_ports {LA_out_p[9]}]
set_property PACKAGE_PIN W7 [get_ports {LA_out_n[9]}]

set_property PACKAGE_PIN AA5 [get_ports {LA_in_p[10]}]
set_property PACKAGE_PIN AB5 [get_ports {LA_in_n[10]}]
set_property PACKAGE_PIN AA8 [get_ports {LA_out_p[10]}]
set_property PACKAGE_PIN AB8 [get_ports {LA_out_n[10]}]

set_property PACKAGE_PIN T1 [get_ports {LA_in_p[11]}]
set_property PACKAGE_PIN U1 [get_ports {LA_in_n[11]}]
set_property PACKAGE_PIN C2 [get_ports {LA_out_p[11]}]
set_property PACKAGE_PIN B2 [get_ports {LA_out_n[11]}]

set_property PACKAGE_PIN N4 [get_ports {LA_in_p[12]}]
set_property PACKAGE_PIN N3 [get_ports {LA_in_n[12]}]
set_property PACKAGE_PIN V9 [get_ports {LA_out_p[12]}]
set_property PACKAGE_PIN V8 [get_ports {LA_out_n[12]}]

set_property PACKAGE_PIN Y3 [get_ports {LA_in_p[13]}]
set_property PACKAGE_PIN AA3 [get_ports {LA_in_n[13]}]
set_property PACKAGE_PIN E1 [get_ports {LA_out_p[13]}]
set_property PACKAGE_PIN D1 [get_ports {LA_out_n[13]}]

set_property PACKAGE_PIN AB7 [get_ports {LA_in_p[14]}]
set_property PACKAGE_PIN AB6 [get_ports {LA_in_n[14]}]
set_property PACKAGE_PIN L5 [get_ports {LA_out_p[14]}]
set_property PACKAGE_PIN L4 [get_ports {LA_out_n[14]}]

set_property PACKAGE_PIN R1 [get_ports {LA_in_p[15]}]
set_property PACKAGE_PIN P1 [get_ports {LA_in_n[15]}]
set_property PACKAGE_PIN B1 [get_ports {LA_out_p[15]}]
set_property PACKAGE_PIN A1 [get_ports {LA_out_n[15]}]

set_property PACKAGE_PIN U2 [get_ports {LA_in_p[16]}]
set_property PACKAGE_PIN V2 [get_ports {LA_in_n[16]}]
set_property PACKAGE_PIN R6 [get_ports {LA_out_p[16]}]
set_property PACKAGE_PIN T6 [get_ports {LA_out_n[16]}]

set_property PACKAGE_PIN AA21 [get_ports {SW_IN[3]}]
set_property PACKAGE_PIN AA20 [get_ports {SW_IN[2]}]
set_property PACKAGE_PIN AA19 [get_ports {SW_IN[1]}]
set_property PACKAGE_PIN AA18 [get_ports {SW_IN[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {SW_IN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_IN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_IN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SW_IN[0]}]

set_property MARK_DEBUG true [get_nets {serdes1/selectio_wiz/inst/data_in_to_device[0]}]
set_property MARK_DEBUG true [get_nets {serdes1/selectio_wiz/inst/data_in_to_device[1]}]
set_property MARK_DEBUG true [get_nets {serdes1/selectio_wiz/inst/data_in_to_device[2]}]
set_property MARK_DEBUG true [get_nets {serdes1/selectio_wiz/inst/data_in_to_device[3]}]
set_property MARK_DEBUG true [get_nets {serdes1/selectio_wiz/inst/data_in_to_device[4]}]
set_property MARK_DEBUG true [get_nets {serdes1/selectio_wiz/inst/data_in_to_device[5]}]
set_property MARK_DEBUG true [get_nets {serdes1/selectio_wiz/inst/data_in_to_device[6]}]
set_property MARK_DEBUG true [get_nets {serdes1/selectio_wiz/inst/data_in_to_device[7]}]
set_property MARK_DEBUG true [get_nets {serdes1/selectio_wiz/inst/data_out_from_device[3]}]
set_property MARK_DEBUG true [get_nets {serdes1/selectio_wiz/inst/data_out_from_device[7]}]
set_property MARK_DEBUG true [get_nets {serdes1/selectio_wiz/inst/data_out_from_device[1]}]
set_property MARK_DEBUG true [get_nets {serdes1/selectio_wiz/inst/data_out_from_device[0]}]
set_property MARK_DEBUG true [get_nets {serdes1/selectio_wiz/inst/data_out_from_device[2]}]
set_property MARK_DEBUG true [get_nets {serdes1/selectio_wiz/inst/data_out_from_device[4]}]
set_property MARK_DEBUG true [get_nets {serdes1/selectio_wiz/inst/data_out_from_device[5]}]
set_property MARK_DEBUG true [get_nets {serdes1/selectio_wiz/inst/data_out_from_device[6]}]

connect_debug_port u_ila_0/clk [get_nets [list clk_BUFG]]
connect_debug_port u_ila_0/probe0 [get_nets [list {serdes1/selectio_wiz/inst/data_in_to_device[0]} {serdes1/selectio_wiz/inst/data_in_to_device[1]} {serdes1/selectio_wiz/inst/data_in_to_device[2]} {serdes1/selectio_wiz/inst/data_in_to_device[3]} {serdes1/selectio_wiz/inst/data_in_to_device[4]} {serdes1/selectio_wiz/inst/data_in_to_device[5]} {serdes1/selectio_wiz/inst/data_in_to_device[6]} {serdes1/selectio_wiz/inst/data_in_to_device[7]}]]
connect_debug_port dbg_hub/clk [get_nets clk_BUFG]

set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[0].serdesii/data_in_to_device[0]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[0].serdesii/data_in_to_device[1]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[0].serdesii/data_in_to_device[2]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[0].serdesii/data_in_to_device[3]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[0].serdesii/data_in_to_device[4]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[0].serdesii/data_in_to_device[5]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[0].serdesii/data_in_to_device[6]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[0].serdesii/data_in_to_device[7]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[1].serdesii/data_in_to_device[0]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[1].serdesii/data_in_to_device[1]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[1].serdesii/data_in_to_device[2]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[1].serdesii/data_in_to_device[3]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[1].serdesii/data_in_to_device[4]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[1].serdesii/data_in_to_device[5]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[1].serdesii/data_in_to_device[6]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[1].serdesii/data_in_to_device[7]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[2].serdesii/data_in_to_device[0]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[2].serdesii/data_in_to_device[1]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[2].serdesii/data_in_to_device[2]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[2].serdesii/data_in_to_device[3]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[2].serdesii/data_in_to_device[4]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[2].serdesii/data_in_to_device[5]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[2].serdesii/data_in_to_device[6]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[2].serdesii/data_in_to_device[7]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[3].serdesii/data_in_to_device[0]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[3].serdesii/data_in_to_device[1]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[3].serdesii/data_in_to_device[2]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[3].serdesii/data_in_to_device[3]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[3].serdesii/data_in_to_device[4]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[3].serdesii/data_in_to_device[5]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[3].serdesii/data_in_to_device[6]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[3].serdesii/data_in_to_device[7]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[4].serdesii/data_in_to_device[0]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[4].serdesii/data_in_to_device[1]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[4].serdesii/data_in_to_device[2]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[4].serdesii/data_in_to_device[3]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[4].serdesii/data_in_to_device[4]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[4].serdesii/data_in_to_device[5]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[4].serdesii/data_in_to_device[6]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[4].serdesii/data_in_to_device[7]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[5].serdesii/data_in_to_device[0]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[5].serdesii/data_in_to_device[1]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[5].serdesii/data_in_to_device[2]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[5].serdesii/data_in_to_device[3]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[5].serdesii/data_in_to_device[4]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[5].serdesii/data_in_to_device[5]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[5].serdesii/data_in_to_device[6]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[5].serdesii/data_in_to_device[7]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[6].serdesii/data_in_to_device[0]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[6].serdesii/data_in_to_device[1]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[6].serdesii/data_in_to_device[2]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[6].serdesii/data_in_to_device[3]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[6].serdesii/data_in_to_device[4]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[6].serdesii/data_in_to_device[5]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[6].serdesii/data_in_to_device[6]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[6].serdesii/data_in_to_device[7]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[7].serdesii/data_in_to_device[0]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[7].serdesii/data_in_to_device[1]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[7].serdesii/data_in_to_device[2]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[7].serdesii/data_in_to_device[3]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[7].serdesii/data_in_to_device[4]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[7].serdesii/data_in_to_device[5]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[7].serdesii/data_in_to_device[6]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[7].serdesii/data_in_to_device[7]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[8].serdesii/data_in_to_device[0]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[8].serdesii/data_in_to_device[1]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[8].serdesii/data_in_to_device[2]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[8].serdesii/data_in_to_device[3]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[8].serdesii/data_in_to_device[4]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[8].serdesii/data_in_to_device[5]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[8].serdesii/data_in_to_device[6]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[8].serdesii/data_in_to_device[7]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[9].serdesii/data_in_to_device[0]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[9].serdesii/data_in_to_device[1]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[9].serdesii/data_in_to_device[2]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[9].serdesii/data_in_to_device[3]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[9].serdesii/data_in_to_device[4]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[9].serdesii/data_in_to_device[5]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[9].serdesii/data_in_to_device[6]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[9].serdesii/data_in_to_device[7]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[10].serdesii/data_in_to_device[0]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[10].serdesii/data_in_to_device[1]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[10].serdesii/data_in_to_device[2]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[10].serdesii/data_in_to_device[3]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[10].serdesii/data_in_to_device[4]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[10].serdesii/data_in_to_device[5]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[10].serdesii/data_in_to_device[6]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[10].serdesii/data_in_to_device[7]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[11].serdesii/data_in_to_device[0]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[11].serdesii/data_in_to_device[1]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[11].serdesii/data_in_to_device[2]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[11].serdesii/data_in_to_device[3]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[11].serdesii/data_in_to_device[4]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[11].serdesii/data_in_to_device[5]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[11].serdesii/data_in_to_device[6]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[11].serdesii/data_in_to_device[7]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[12].serdesii/data_in_to_device[0]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[12].serdesii/data_in_to_device[1]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[12].serdesii/data_in_to_device[2]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[12].serdesii/data_in_to_device[3]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[12].serdesii/data_in_to_device[4]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[12].serdesii/data_in_to_device[5]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[12].serdesii/data_in_to_device[6]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[12].serdesii/data_in_to_device[7]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[13].serdesii/data_in_to_device[0]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[13].serdesii/data_in_to_device[1]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[13].serdesii/data_in_to_device[2]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[13].serdesii/data_in_to_device[3]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[13].serdesii/data_in_to_device[4]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[13].serdesii/data_in_to_device[5]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[13].serdesii/data_in_to_device[6]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[13].serdesii/data_in_to_device[7]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[14].serdesii/data_in_to_device[0]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[14].serdesii/data_in_to_device[1]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[14].serdesii/data_in_to_device[2]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[14].serdesii/data_in_to_device[3]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[14].serdesii/data_in_to_device[4]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[14].serdesii/data_in_to_device[5]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[14].serdesii/data_in_to_device[6]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[14].serdesii/data_in_to_device[7]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[15].serdesii/data_in_to_device[0]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[15].serdesii/data_in_to_device[1]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[15].serdesii/data_in_to_device[2]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[15].serdesii/data_in_to_device[3]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[15].serdesii/data_in_to_device[4]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[15].serdesii/data_in_to_device[5]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[15].serdesii/data_in_to_device[6]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[15].serdesii/data_in_to_device[7]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[16].serdesii/data_in_to_device[0]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[16].serdesii/data_in_to_device[1]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[16].serdesii/data_in_to_device[2]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[16].serdesii/data_in_to_device[3]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[16].serdesii/data_in_to_device[4]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[16].serdesii/data_in_to_device[5]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[16].serdesii/data_in_to_device[6]}]
set_property MARK_DEBUG true [get_nets {g_GENERATE_FOR[16].serdesii/data_in_to_device[7]}]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_wiz/inst/clk_out2]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {g_GENERATE_FOR[0].serdesii/data_in_to_device[0]} {g_GENERATE_FOR[0].serdesii/data_in_to_device[1]} {g_GENERATE_FOR[0].serdesii/data_in_to_device[2]} {g_GENERATE_FOR[0].serdesii/data_in_to_device[3]} {g_GENERATE_FOR[0].serdesii/data_in_to_device[4]} {g_GENERATE_FOR[0].serdesii/data_in_to_device[5]} {g_GENERATE_FOR[0].serdesii/data_in_to_device[6]} {g_GENERATE_FOR[0].serdesii/data_in_to_device[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {g_GENERATE_FOR[10].serdesii/data_in_to_device[0]} {g_GENERATE_FOR[10].serdesii/data_in_to_device[1]} {g_GENERATE_FOR[10].serdesii/data_in_to_device[2]} {g_GENERATE_FOR[10].serdesii/data_in_to_device[3]} {g_GENERATE_FOR[10].serdesii/data_in_to_device[4]} {g_GENERATE_FOR[10].serdesii/data_in_to_device[5]} {g_GENERATE_FOR[10].serdesii/data_in_to_device[6]} {g_GENERATE_FOR[10].serdesii/data_in_to_device[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 8 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {g_GENERATE_FOR[11].serdesii/data_in_to_device[0]} {g_GENERATE_FOR[11].serdesii/data_in_to_device[1]} {g_GENERATE_FOR[11].serdesii/data_in_to_device[2]} {g_GENERATE_FOR[11].serdesii/data_in_to_device[3]} {g_GENERATE_FOR[11].serdesii/data_in_to_device[4]} {g_GENERATE_FOR[11].serdesii/data_in_to_device[5]} {g_GENERATE_FOR[11].serdesii/data_in_to_device[6]} {g_GENERATE_FOR[11].serdesii/data_in_to_device[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 8 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {g_GENERATE_FOR[4].serdesii/data_in_to_device[0]} {g_GENERATE_FOR[4].serdesii/data_in_to_device[1]} {g_GENERATE_FOR[4].serdesii/data_in_to_device[2]} {g_GENERATE_FOR[4].serdesii/data_in_to_device[3]} {g_GENERATE_FOR[4].serdesii/data_in_to_device[4]} {g_GENERATE_FOR[4].serdesii/data_in_to_device[5]} {g_GENERATE_FOR[4].serdesii/data_in_to_device[6]} {g_GENERATE_FOR[4].serdesii/data_in_to_device[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 8 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {g_GENERATE_FOR[5].serdesii/data_in_to_device[0]} {g_GENERATE_FOR[5].serdesii/data_in_to_device[1]} {g_GENERATE_FOR[5].serdesii/data_in_to_device[2]} {g_GENERATE_FOR[5].serdesii/data_in_to_device[3]} {g_GENERATE_FOR[5].serdesii/data_in_to_device[4]} {g_GENERATE_FOR[5].serdesii/data_in_to_device[5]} {g_GENERATE_FOR[5].serdesii/data_in_to_device[6]} {g_GENERATE_FOR[5].serdesii/data_in_to_device[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 8 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {g_GENERATE_FOR[6].serdesii/data_in_to_device[0]} {g_GENERATE_FOR[6].serdesii/data_in_to_device[1]} {g_GENERATE_FOR[6].serdesii/data_in_to_device[2]} {g_GENERATE_FOR[6].serdesii/data_in_to_device[3]} {g_GENERATE_FOR[6].serdesii/data_in_to_device[4]} {g_GENERATE_FOR[6].serdesii/data_in_to_device[5]} {g_GENERATE_FOR[6].serdesii/data_in_to_device[6]} {g_GENERATE_FOR[6].serdesii/data_in_to_device[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 8 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {g_GENERATE_FOR[7].serdesii/data_in_to_device[0]} {g_GENERATE_FOR[7].serdesii/data_in_to_device[1]} {g_GENERATE_FOR[7].serdesii/data_in_to_device[2]} {g_GENERATE_FOR[7].serdesii/data_in_to_device[3]} {g_GENERATE_FOR[7].serdesii/data_in_to_device[4]} {g_GENERATE_FOR[7].serdesii/data_in_to_device[5]} {g_GENERATE_FOR[7].serdesii/data_in_to_device[6]} {g_GENERATE_FOR[7].serdesii/data_in_to_device[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 8 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {g_GENERATE_FOR[12].serdesii/data_in_to_device[0]} {g_GENERATE_FOR[12].serdesii/data_in_to_device[1]} {g_GENERATE_FOR[12].serdesii/data_in_to_device[2]} {g_GENERATE_FOR[12].serdesii/data_in_to_device[3]} {g_GENERATE_FOR[12].serdesii/data_in_to_device[4]} {g_GENERATE_FOR[12].serdesii/data_in_to_device[5]} {g_GENERATE_FOR[12].serdesii/data_in_to_device[6]} {g_GENERATE_FOR[12].serdesii/data_in_to_device[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 8 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {g_GENERATE_FOR[9].serdesii/data_in_to_device[0]} {g_GENERATE_FOR[9].serdesii/data_in_to_device[1]} {g_GENERATE_FOR[9].serdesii/data_in_to_device[2]} {g_GENERATE_FOR[9].serdesii/data_in_to_device[3]} {g_GENERATE_FOR[9].serdesii/data_in_to_device[4]} {g_GENERATE_FOR[9].serdesii/data_in_to_device[5]} {g_GENERATE_FOR[9].serdesii/data_in_to_device[6]} {g_GENERATE_FOR[9].serdesii/data_in_to_device[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 8 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {g_GENERATE_FOR[8].serdesii/data_in_to_device[0]} {g_GENERATE_FOR[8].serdesii/data_in_to_device[1]} {g_GENERATE_FOR[8].serdesii/data_in_to_device[2]} {g_GENERATE_FOR[8].serdesii/data_in_to_device[3]} {g_GENERATE_FOR[8].serdesii/data_in_to_device[4]} {g_GENERATE_FOR[8].serdesii/data_in_to_device[5]} {g_GENERATE_FOR[8].serdesii/data_in_to_device[6]} {g_GENERATE_FOR[8].serdesii/data_in_to_device[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 8 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {g_GENERATE_FOR[13].serdesii/data_in_to_device[0]} {g_GENERATE_FOR[13].serdesii/data_in_to_device[1]} {g_GENERATE_FOR[13].serdesii/data_in_to_device[2]} {g_GENERATE_FOR[13].serdesii/data_in_to_device[3]} {g_GENERATE_FOR[13].serdesii/data_in_to_device[4]} {g_GENERATE_FOR[13].serdesii/data_in_to_device[5]} {g_GENERATE_FOR[13].serdesii/data_in_to_device[6]} {g_GENERATE_FOR[13].serdesii/data_in_to_device[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 8 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {g_GENERATE_FOR[14].serdesii/data_in_to_device[0]} {g_GENERATE_FOR[14].serdesii/data_in_to_device[1]} {g_GENERATE_FOR[14].serdesii/data_in_to_device[2]} {g_GENERATE_FOR[14].serdesii/data_in_to_device[3]} {g_GENERATE_FOR[14].serdesii/data_in_to_device[4]} {g_GENERATE_FOR[14].serdesii/data_in_to_device[5]} {g_GENERATE_FOR[14].serdesii/data_in_to_device[6]} {g_GENERATE_FOR[14].serdesii/data_in_to_device[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 8 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {g_GENERATE_FOR[15].serdesii/data_in_to_device[0]} {g_GENERATE_FOR[15].serdesii/data_in_to_device[1]} {g_GENERATE_FOR[15].serdesii/data_in_to_device[2]} {g_GENERATE_FOR[15].serdesii/data_in_to_device[3]} {g_GENERATE_FOR[15].serdesii/data_in_to_device[4]} {g_GENERATE_FOR[15].serdesii/data_in_to_device[5]} {g_GENERATE_FOR[15].serdesii/data_in_to_device[6]} {g_GENERATE_FOR[15].serdesii/data_in_to_device[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 8 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {g_GENERATE_FOR[16].serdesii/data_in_to_device[0]} {g_GENERATE_FOR[16].serdesii/data_in_to_device[1]} {g_GENERATE_FOR[16].serdesii/data_in_to_device[2]} {g_GENERATE_FOR[16].serdesii/data_in_to_device[3]} {g_GENERATE_FOR[16].serdesii/data_in_to_device[4]} {g_GENERATE_FOR[16].serdesii/data_in_to_device[5]} {g_GENERATE_FOR[16].serdesii/data_in_to_device[6]} {g_GENERATE_FOR[16].serdesii/data_in_to_device[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 8 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {g_GENERATE_FOR[1].serdesii/data_in_to_device[0]} {g_GENERATE_FOR[1].serdesii/data_in_to_device[1]} {g_GENERATE_FOR[1].serdesii/data_in_to_device[2]} {g_GENERATE_FOR[1].serdesii/data_in_to_device[3]} {g_GENERATE_FOR[1].serdesii/data_in_to_device[4]} {g_GENERATE_FOR[1].serdesii/data_in_to_device[5]} {g_GENERATE_FOR[1].serdesii/data_in_to_device[6]} {g_GENERATE_FOR[1].serdesii/data_in_to_device[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 8 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {g_GENERATE_FOR[2].serdesii/data_in_to_device[0]} {g_GENERATE_FOR[2].serdesii/data_in_to_device[1]} {g_GENERATE_FOR[2].serdesii/data_in_to_device[2]} {g_GENERATE_FOR[2].serdesii/data_in_to_device[3]} {g_GENERATE_FOR[2].serdesii/data_in_to_device[4]} {g_GENERATE_FOR[2].serdesii/data_in_to_device[5]} {g_GENERATE_FOR[2].serdesii/data_in_to_device[6]} {g_GENERATE_FOR[2].serdesii/data_in_to_device[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 8 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list {g_GENERATE_FOR[3].serdesii/data_in_to_device[0]} {g_GENERATE_FOR[3].serdesii/data_in_to_device[1]} {g_GENERATE_FOR[3].serdesii/data_in_to_device[2]} {g_GENERATE_FOR[3].serdesii/data_in_to_device[3]} {g_GENERATE_FOR[3].serdesii/data_in_to_device[4]} {g_GENERATE_FOR[3].serdesii/data_in_to_device[5]} {g_GENERATE_FOR[3].serdesii/data_in_to_device[6]} {g_GENERATE_FOR[3].serdesii/data_in_to_device[7]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets slow_clk]
