# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/atfc.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system}]

# IP: bd/system/ip/system_axi_iic_0_0/system_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_iic_0_0 || ORIG_REF_NAME==system_axi_iic_0_0}]

# IP: bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_uartlite_0_0 || ORIG_REF_NAME==system_axi_uartlite_0_0}]

# IP: bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xadc_wiz_0_0 || ORIG_REF_NAME==system_xadc_wiz_0_0}]

# IP: bd/system/ip/system_microblaze_0_1/system_microblaze_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_microblaze_0_1 || ORIG_REF_NAME==system_microblaze_0_1}]

# IP: bd/system/ip/system_rst_Clk_100M_1/system_rst_Clk_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_Clk_100M_1 || ORIG_REF_NAME==system_rst_Clk_100M_1}]

# IP: bd/system/ip/system_microblaze_0_axi_periph_0/system_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_microblaze_0_axi_periph_0 || ORIG_REF_NAME==system_microblaze_0_axi_periph_0}]

# IP: bd/system/ip/system_microblaze_0_axi_intc_1/system_microblaze_0_axi_intc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_microblaze_0_axi_intc_1 || ORIG_REF_NAME==system_microblaze_0_axi_intc_1}]

# IP: bd/system/ip/system_microblaze_0_xlconcat_1/system_microblaze_0_xlconcat_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_microblaze_0_xlconcat_1 || ORIG_REF_NAME==system_microblaze_0_xlconcat_1}]

# IP: bd/system/ip/system_mdm_1_0/system_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_mdm_1_0 || ORIG_REF_NAME==system_mdm_1_0}]

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0}]

# IP: bd/system/ip/system_dlmb_v10_0/system_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dlmb_v10_0 || ORIG_REF_NAME==system_dlmb_v10_0}]

# IP: bd/system/ip/system_ilmb_v10_0/system_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ilmb_v10_0 || ORIG_REF_NAME==system_ilmb_v10_0}]

# IP: bd/system/ip/system_dlmb_bram_if_cntlr_0/system_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==system_dlmb_bram_if_cntlr_0}]

# IP: bd/system/ip/system_ilmb_bram_if_cntlr_0/system_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==system_ilmb_bram_if_cntlr_0}]

# IP: bd/system/ip/system_lmb_bram_0/system_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_lmb_bram_0 || ORIG_REF_NAME==system_lmb_bram_0}]

# IP: bd/system/ip/system_selectio_wiz_0_0/system_selectio_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_selectio_wiz_0_0 || ORIG_REF_NAME==system_selectio_wiz_0_0}]

# IP: bd/system/ip/system_xlconstant_0_0/system_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_0 || ORIG_REF_NAME==system_xlconstant_0_0}]

# IP: bd/system/ip/system_selectio_wiz_0_1/system_selectio_wiz_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_selectio_wiz_0_1 || ORIG_REF_NAME==system_selectio_wiz_0_1}]

# IP: bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_0 || ORIG_REF_NAME==system_axi_gpio_0_0}]

# XDC: bd/system/system_ooc.xdc
