# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/smkilani/Documents/atfc/firmware/ATFC_serdes_fmc/ATFC_serdes_fmc.srcs/sources_1/ip/selectio_wiz_1/selectio_wiz_1.xci
# IP: The module: 'selectio_wiz_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/smkilani/Documents/atfc/firmware/ATFC_serdes_fmc/ATFC_serdes_fmc.srcs/sources_1/ip/selectio_wiz_1/selectio_wiz_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'selectio_wiz_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/smkilani/Documents/atfc/firmware/ATFC_serdes_fmc/ATFC_serdes_fmc.srcs/sources_1/ip/selectio_wiz_1/selectio_wiz_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'selectio_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/Users/smkilani/Documents/atfc/firmware/ATFC_serdes_fmc/ATFC_serdes_fmc.srcs/sources_1/ip/selectio_wiz_1/selectio_wiz_1.xci
# IP: The module: 'selectio_wiz_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/smkilani/Documents/atfc/firmware/ATFC_serdes_fmc/ATFC_serdes_fmc.srcs/sources_1/ip/selectio_wiz_1/selectio_wiz_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'selectio_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/smkilani/Documents/atfc/firmware/ATFC_serdes_fmc/ATFC_serdes_fmc.srcs/sources_1/ip/selectio_wiz_1/selectio_wiz_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'selectio_wiz_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
